language: node_js

node_js:
  - '8'

install:
  - 'npm install'
  - 'cd $TRAVIS_BUILD_DIR/renderers/renderer-jsdom/ && npm install'
  - 'cd $TRAVIS_BUILD_DIR/renderers/renderer-puppeteer/ && npm install'
  - 'cd $TRAVIS_BUILD_DIR'

notifications:
  email: false
